import { UI } from './state.js';

export const poseState = {
  active: false,
  isCalibrating: false,
  isBodyReady: false,
  isPaired: false,      // True when user clicked "GÖVDEYİ EŞLEŞTİR"
  roll: 0,             // Roll angle in radians (clamped)
  flapImpulse: 0,      // Upward impulse generated by arm strokes
  isDiving: false,     // Arms tucked down for fast dive
  armLiftLeft: 0,      // Real-time arm lift: >0 raised, <0 dropped
  armLiftRight: 0,
  baselineRoll: 0,
  baselineShoulderY: 0.5,
  lastWristY: 0.5
};

const videoElement = UI.video;
let mediaStream = null;
let isProcessingFrame = false;
let isCameraRunning = false;
let animFrameId = null;
let cachedLandmarks = null;
let lastVideoTime = -1;

// Initialize MediaPipe Pose with Lite model (0 = high-speed real-time, zero freeze)
const pose = new Pose({
  locateFile: (file) => `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`
});

pose.setOptions({
  modelComplexity: 0, // 0 = Lite (Ultra-fast, smooth 60fps, no frame drops)
  smoothLandmarks: true,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5
});

// Render upper-body skeleton with glow
function drawSkeleton(ctx, canvas, lm, isReady) {
  const w = canvas.width;
  const h = canvas.height;

  // Upper body bone pairs
  const connections = [
    [11, 12],           // Shoulders
    [11, 13], [13, 15], // Left Arm
    [12, 14], [14, 16], // Right Arm
    [11, 23], [12, 24], [23, 24] // Torso
  ];

  ctx.lineWidth = 3.5;
  ctx.strokeStyle = isReady ? '#2ecc71' : '#f39c12';
  ctx.shadowColor = isReady ? 'rgba(46, 204, 113, 0.6)' : 'rgba(243, 156, 18, 0.6)';
  ctx.shadowBlur = 8;

  connections.forEach(([i, j]) => {
    const p1 = lm[i];
    const p2 = lm[j];
    if (p1 && p2 && (p1.visibility || 1) > 0.4 && (p2.visibility || 1) > 0.4) {
      ctx.beginPath();
      ctx.moveTo(p1.x * w, p1.y * h);
      ctx.lineTo(p2.x * w, p2.y * h);
      ctx.stroke();
    }
  });

  // Wing span guide line across wrists
  if (lm[15] && lm[16]) {
    ctx.save();
    ctx.setLineDash([4, 4]);
    ctx.strokeStyle = '#58a6ff';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(lm[15].x * w, lm[15].y * h);
    ctx.lineTo(lm[16].x * w, lm[16].y * h);
    ctx.stroke();
    ctx.restore();
  }

  // Glowing joint markers
  const joints = [11, 12, 13, 14, 15, 16];
  joints.forEach(idx => {
    const pt = lm[idx];
    if (pt && (pt.visibility || 1) > 0.4) {
      ctx.beginPath();
      ctx.arc(pt.x * w, pt.y * h, 6, 0, 2 * Math.PI);
      ctx.fillStyle = '#f1c40f';
      ctx.fill();
      ctx.lineWidth = 2;
      ctx.strokeStyle = '#ffffff';
      ctx.stroke();
    }
  });

  ctx.shadowBlur = 0;
}

// MediaPipe Pose processing callback
pose.onResults((results) => {
  if (!results.poseLandmarks) {
    cachedLandmarks = null;
    if (poseState.isCalibrating) updateCalibrationBadgeUI(null);
    return;
  }

  cachedLandmarks = results.poseLandmarks;
  const lm = results.poseLandmarks;
  const lSh = lm[11];
  const rSh = lm[12];
  const lWr = lm[15];
  const rWr = lm[16];

  // Calculate shoulder roll angle (vector from Right shoulder to Left shoulder)
  // In camera image: rSh is on left (smaller X), lSh is on right (larger X)
  const dx = lSh.x - rSh.x;
  const dy = lSh.y - rSh.y;
  let rawRoll = Math.atan2(dy, dx);
  rawRoll = Math.max(-0.45, Math.min(0.45, rawRoll));
  poseState.currentRawRoll = rawRoll;

  // Arm heights relative to shoulders
  const shoulderWidth = Math.max(0.15, Math.hypot(dx, dy));
  const dyLeft = (lWr.y - lSh.y);
  const dyRight = (rWr.y - rSh.y);

  // Smooth arm lifts (-1.0 to +1.0)
  const targetLiftLeft = -(dyLeft / shoulderWidth);
  const targetLiftRight = -(dyRight / shoulderWidth);
  poseState.armLiftLeft += (targetLiftLeft - poseState.armLiftLeft) * 0.35;
  poseState.armLiftRight += (targetLiftRight - poseState.armLiftRight) * 0.35;

  // 1. Calibration / Pairing Mode (Before flight takeoff)
  if (poseState.isCalibrating) {
    const shouldersOk = lSh && rSh && (lSh.visibility || 1) > 0.55 && (rSh.visibility || 1) > 0.55;
    const armsOk = lWr && rWr && (lWr.visibility || 1) > 0.40 && (rWr.visibility || 1) > 0.40;
    poseState.isBodyReady = shouldersOk && armsOk;

    if (poseState.isBodyReady) {
      if (!poseState.isPaired) {
        // Continuously align baseline to user's natural resting stance
        poseState.baselineRoll = rawRoll;
        poseState.baselineShoulderY = (lSh.y + rSh.y) / 2;
        poseState.roll = 0;
      } else {
        let diff = rawRoll - poseState.baselineRoll;
        // Soft ~3-degree deadzone around neutral so resting posture snaps strictly to 0°
        if (Math.abs(diff) < 0.055) {
          diff = 0;
        } else {
          diff = (diff > 0 ? diff - 0.055 : diff + 0.055);
        }
        poseState.roll = Math.max(-0.65, Math.min(0.65, diff));
      }
    } else {
      poseState.roll = 0;
    }

    const currentDeg = Math.round((poseState.roll * 180) / Math.PI);
    updateCalibrationBadgeUI({ shouldersOk, armsOk, displayRollDeg: currentDeg, isReady: poseState.isBodyReady });
    return;
  }

  // 2. In-Flight Pose Mode
  if (poseState.active) {
    // Dynamic adaptive neutral drift:
    // If player holds a steady posture (micro variations < 0.012 rad),
    // baseline gently tracks the resting stance so natural slope NEVER causes drift!
    if (poseState.lastRawRoll !== undefined) {
      const rollDelta = Math.abs(rawRoll - poseState.lastRawRoll);
      if (rollDelta < 0.012) {
        poseState.baselineRoll += (rawRoll - poseState.baselineRoll) * 0.04;
      }
    }
    poseState.lastRawRoll = rawRoll;

    // Roll angle relative to calibrated baseline with an 8.5-degree deadzone
    let diff = rawRoll - poseState.baselineRoll;
    if (Math.abs(diff) < 0.15) {
      diff = 0;
    } else {
      diff = (diff > 0 ? diff - 0.15 : diff + 0.15);
    }
    const calibratedRoll = Math.max(-0.75, Math.min(0.75, diff));
    poseState.roll += (calibratedRoll - poseState.roll) * 0.28;

    // Wing & Wrist kinematics
    const avgWristY = (lWr.y + rWr.y) / 2;
    const avgShoulderY = (lSh.y + rSh.y) / 2;

    // Downstroke wing pump: generates lift on quick downward arm thrusts
    const downstrokeSpeed = avgWristY - poseState.lastWristY;
    if (downstrokeSpeed > 0.032) {
      poseState.flapImpulse = 6.2;
    }
    poseState.lastWristY = avgWristY;

    // Sustained glide lift: arms held higher than shoulders
    if (avgWristY < avgShoulderY - 0.05) {
      const glideLift = (avgShoulderY - avgWristY) * 3.8;
      poseState.flapImpulse = Math.max(poseState.flapImpulse, glideLift);
    }

    // Falcon dive posture: wrists tucked lower than chest/hips
    poseState.isDiving = avgWristY > avgShoulderY + 0.18;
  }
});

function updateCalibrationBadgeUI(data) {
  if (!data) {
    UI.badgeShoulders?.classList.remove('active');
    UI.badgeArms?.classList.remove('active');
    UI.badgeStatus?.classList.remove('active');
    if (UI.calibStartBtn) {
      UI.calibStartBtn.disabled = true;
      UI.calibStartBtn.innerText = "KAMERA BEKLENİYOR...";
    }
    return;
  }

  const { shouldersOk, armsOk, displayRollDeg, isReady } = data;

  if (UI.badgeShoulders) {
    UI.badgeShoulders.classList.toggle('active', shouldersOk);
    const span = UI.badgeShoulders.querySelector('span:last-child');
    if (span) span.innerText = shouldersOk ? "Omuzlar: Hazır" : "Omuzlar: Bekleniyor...";
  }

  if (UI.badgeArms) {
    UI.badgeArms.classList.toggle('active', armsOk);
    const span = UI.badgeArms.querySelector('span:last-child');
    if (span) span.innerText = armsOk ? "Kanatlar: Açık" : "Kanatlar: Açın";
  }

  if (UI.badgeRoll) {
    const deg = (displayRollDeg !== undefined) ? displayRollDeg : Math.round((poseState.roll * 180) / Math.PI);
    UI.badgeRoll.classList.add('active');
    const span = UI.badgeRoll.querySelector('span:last-child');
    if (span) span.innerText = `Duruş: ${deg}°`;
  }

  if (UI.badgeStatus) {
    UI.badgeStatus.classList.toggle('active', isReady);
    const span = UI.badgeStatus.querySelector('span:last-child');
    if (span) {
      if (!isReady) span.innerText = "Duruş: Bekleniyor";
      else if (!poseState.isPaired) span.innerText = "Eşleşmeye Hazır";
      else span.innerText = "Eşleştirildi (Canlı)";
    }
  }

  if (UI.calibStartBtn) {
    if (!isReady) {
      UI.calibStartBtn.disabled = true;
      UI.calibStartBtn.innerText = "DURUŞ BEKLENİYOR...";
      UI.calibStartBtn.classList.remove('btn-hero');
    } else if (!poseState.isPaired) {
      UI.calibStartBtn.disabled = false;
      UI.calibStartBtn.innerText = "GÖVDEYİ EŞLEŞTİR ⚡";
      UI.calibStartBtn.classList.add('btn-hero');
    } else {
      UI.calibStartBtn.disabled = false;
      UI.calibStartBtn.innerText = "UÇUŞA BAŞLA 🦅";
      UI.calibStartBtn.classList.add('btn-hero');
    }
  }
}

// Start webcam stream using native browser getUserMedia + 60fps decoupled render loop
export async function startCamera() {
  if (!mediaStream) {
    mediaStream = await navigator.mediaDevices.getUserMedia({
      video: { width: { ideal: 640 }, height: { ideal: 480 }, facingMode: 'user' },
      audio: false
    });
    videoElement.srcObject = mediaStream;
    await videoElement.play();
  }
  isCameraRunning = true;

  function step() {
    if (!isCameraRunning) return;

    if (videoElement.readyState >= 2) {
      const activeCanvas = poseState.isCalibrating ? UI.calibCanvas : UI.camCanvas;
      if (activeCanvas) {
        const ctx = activeCanvas.getContext('2d');
        if (ctx) {
          if (activeCanvas.width !== videoElement.videoWidth && videoElement.videoWidth > 0) {
            activeCanvas.width = videoElement.videoWidth;
            activeCanvas.height = videoElement.videoHeight;
          }
          // Direct 60 FPS live video draw: never freezes!
          ctx.drawImage(videoElement, 0, 0, activeCanvas.width, activeCanvas.height);

          // Overlay skeleton if available
          if (cachedLandmarks) {
            drawSkeleton(ctx, activeCanvas, cachedLandmarks, poseState.isBodyReady);
          }
        }
      }

      // Asynchronous non-blocking inference
      if (!isProcessingFrame && videoElement.currentTime !== lastVideoTime) {
        isProcessingFrame = true;
        lastVideoTime = videoElement.currentTime;
        pose.send({ image: videoElement })
          .catch(e => console.warn("Pose error:", e))
          .finally(() => { isProcessingFrame = false; });
      }
    }

    animFrameId = requestAnimationFrame(step);
  }
  step();
}

export function stopCamera() {
  if (animFrameId) cancelAnimationFrame(animFrameId);
  if (mediaStream) {
    mediaStream.getTracks().forEach(t => t.stop());
    mediaStream = null;
  }
  isCameraRunning = false;
  poseState.active = false;
  poseState.isCalibrating = false;
  poseState.isPaired = false;
}
